- name: 下载helm客户端
  copy: src={{ BASE_HELM_DIR }}/helm dest={{ BIN_DIR }}/helm mode=0755

- name: 自动补全
  shell: echo "source <(helm completion bash)" > /etc/profile.d/helm.sh

- name: 准备rbac配置
  template: src=helm-rbac.yaml.j2 dest={{ K8S_YAML_DIR }}/helm-rbac.yaml

- name: 在k8s上创建rbac
  shell: "{{ BASE_K8S_DIR }}/kubectl apply -f {{ K8S_YAML_DIR }}/helm-rbac.yaml"
  ignore_errors: true

- name: 安装tiller
  shell: "{{ BIN_DIR }}/helm init \
        --upgrade --force-upgrade \
        --service-account {{ tiller_sa }} \
        --tiller-namespace {{ helm_namespace }} \
        --tiller-image {{ tiller_image }} \
        --stable-repo-url {{ repo_url }}"
  ignore_errors: true

- name: 以轮询的方式等待helm服务启动完成
  command: "{{ BASE_HELM_DIR }}/helm ls"
  register: result
  until:    result.rc == 0
  retries:  5
  delay: 6
  delegate_to: "{{ groups.deploy[0] }}"
  run_once: True
