# to create CA, kubeconfig, kube-proxy.kubeconfig etc. on 'deploy' node
- hosts: deploy
  roles:
  - deploy

#  [optional] to install loadbalance service, only needed by multi-master cluster 
#- hosts: lb
#  roles:
#  - lb
#
# prepare tasks for all nodes
- hosts:
  - kube-master
  - kube-node
  - etcd
#  - lb
  roles:
  - prepare

