# 国内镜像加速

REG_MIRROR_1: "https://mus1g88v.mirror.aliyuncs.com"
REG_MIRROR_2: "http://f1361db2.m.daocloud.io"

# docker日志相关

LOG_DRIVER: "json-file"
LOG_LEVEL: "warn"
LOG_MAX_SIZE: "10m"
LOG_MAX_FILE: 3

# docker容器存储目录
STORAGE_DIR: "/var/lib/docker"
