- hosts: deploy
  tasks:
  - name: 在deploy 节点创建相关目录
    file: path={{ K8S_YAML_DIR }} state=directory
  
  - name: 下载 group:read rbac 文件
    copy: src=read-group-rbac.yaml dest={{ K8S_YAML_DIR }}/read-group-rbac.yaml
  
  - name: 创建group:read rbac 绑定
    shell: "{{ BIN_DIR }}/kubectl apply -f {{ K8S_YAML_DIR }}/read-group-rbac.yaml"
  
  - name: 删除原有kubeconfig
    file: path=/root/.kube state=absent

  # 创建readonly kubectl kubeconfig文件: /root/.kube/config
  - name: 准备kubectl使用的read 证书签名请求
    template: src=read-csr.json.j2 dest={{ CA_DIR }}/read-csr.json
  
  - name: 创建 read证书与私钥
    shell: "cd {{ CA_DIR }} && {{ BIN_DIR }}/cfssl gencert \
          -ca={{ CA_DIR }}/ca.pem \
          -ca-key={{ CA_DIR }}/ca-key.pem \
          -config={{ CA_DIR }}/ca-config.json \
          -profile=kubernetes read-csr.json | {{ BIN_DIR }}/cfssljson -bare read"
  # 设置集群参数，指定CA证书和apiserver地址
  - name: 设置集群参数
    shell: "{{ BIN_DIR }}/kubectl config set-cluster kubernetes \
          --certificate-authority={{ CA_DIR }}/ca.pem \
          --embed-certs=true \
          --server={{ KUBE_APISERVER }}"
  # 设置客户端认证参数，指定使用read证书和私钥
  - name: 设置客户端认证参数
    shell: "{{ BIN_DIR }}/kubectl config set-credentials read \
          --client-certificate={{ CA_DIR }}/read.pem \
          --embed-certs=true \
          --client-key={{ CA_DIR }}/read-key.pem"
  # 设置上下文参数，说明使用cluster集群和用户read
  - name: 设置上下文参数
    shell: "{{ BIN_DIR }}/kubectl config set-context kubernetes \
          --cluster=kubernetes --user=read"
  # 选择默认上下文
  - name: 选择默认上下文
    shell: "{{ BIN_DIR }}/kubectl config use-context kubernetes"
  
