- name: 准备alicloud-nas配置目录
  file: name={{ K8S_YAML_DIR }}/storage/alicloud-nas state=directory

- name: 生成alicloud-nas动态存储配置
  template:
    src: alicloud-nas/alicloud-nas.yaml.j2
    dest: "{{ K8S_YAML_DIR }}/storage/alicloud-nas/{{ storage.aliyun_nas.controller_name }}.yaml"

#- name: 复制alicloud-disk配置
#  copy:
#    src: alicloud-disk.yaml
#    dest: "{{ BASE_DIR }}/manifests/storage/alicloud-nas/alicloud-disk.yaml"

#- name: 开始部署alicloud-disk存储
#  shell: "{{ BIN_DIR }}/kubectl apply -f {{ BASE_DIR }}/manifests/storage/alicloud-nas/alicloud-disk.yaml"

- name: 开始部署alicloud-nas动态存储
  shell: "{{ BIN_DIR }}/kubectl apply -f {{ K8S_YAML_DIR }}/storage/alicloud-nas/{{ storage.aliyun_nas.controller_name }}.yaml"
