- name: 准备nfs-client 配置目录
  file: name={{ BASE_DIR }}/manifests/storage/nfs state=directory

- name: 生成nfs-client动态存储配置
  template:
    src: nfs/nfs-client-provisioner.yaml.j2
    dest: "{{ BASE_DIR }}/manifests/storage/nfs/{{ storage.nfs.provisioner_name }}.yaml"

- name: 开始部署nfs-client动态存储
  shell: "{{ BIN_DIR }}/kubectl apply -f {{ BASE_DIR }}/manifests/storage/nfs/{{ storage.nfs.provisioner_name }}.yaml"
