# 系统基础软件环境
- import_tasks: centos.yml
  when: ansible_distribution == "CentOS"

- name: prepare some dirs
  file: name={{ item }} state=directory
  with_items:
  - "{{ BIN_DIR }}"
  - "{{ CA_DIR }}"
  - /root/.kube

- name: 分发证书工具 CFSSL
  copy: src={{ BASE_CFSSL_DIR }}/{{ item }} dest={{ BIN_DIR }}/{{ item }} mode=0755
  with_items:
  - cfssl
  - cfssl-certinfo
  - cfssljson

- name: 分发 kubectl
  copy: src={{ BASE_K8S_DIR }}/kubectl dest={{ BIN_DIR }}/kubectl mode=0755
  tags: upgrade_k8s

- name: 分发 kubeconfig配置文件
  synchronize: src=/root/.kube/config dest=/root/.kube/config
  delegate_to: "{{ groups.deploy[0] }}"

- name: 分发证书相关
  synchronize: src={{ CA_DIR }}/{{ item }} dest={{ CA_DIR }}/{{ item }}
  with_items:
  - admin.pem
  - admin-key.pem
  - ca.pem
  - ca-key.pem
  - ca.csr
  - ca-config.json
  delegate_to: "{{ groups.deploy[0] }}"

# 公共系统参数设置
- import_tasks: common.yml

- import_tasks: centos-kernel.yml
  when: ansible_distribution == "CentOS"
