- block:
    - name: 在deploy 节点创建相关目录
      file: name={{ K8S_YAML_DIR }}/flannel state=directory

    - name: 配置 flannel DaemonSet yaml文件
      template: src=kube-flannel.yaml.j2 dest={{ K8S_YAML_DIR }}/flannel/kube-flannel.yaml
  delegate_to: "{{ groups.deploy[0] }}"
  run_once: true
    
- name: 创建flannel cni 相关目录
  file: name={{ item }} state=directory
  with_items:
  - "{{ CNI_NET_DIR }}"

- name: 下载flannel cni plugins
  copy: src={{ BASE_CNI_DIR }}/{{ item }} dest={{ BIN_DIR }}/{{ item }} mode=0755
  with_items:
  - bridge
  - flannel
  - host-local
  - loopback
  - portmap

# 只需单节点执行一次
- name: 运行 flannel网络
  shell: "{{ BASE_K8S_DIR }}/kubectl apply -f {{ K8S_YAML_DIR }}/flannel/ && sleep 5"
  delegate_to: "{{ groups.deploy[0] }}"
  run_once: true

# 删除原有cni配置
- name: 删除默认cni配置
  file: path={{ CNI_NET_DIR }}/10-default.conf state=absent

# 等待网络插件部署成功，视下载镜像速度而定
- name: 轮询等待flannel 运行，视下载镜像速度而定
  shell: "{{ BASE_K8S_DIR }}/kubectl get pod -n kube-system -o wide|grep 'flannel'|grep ' {{ inventory_hostname }} '|awk '{print $3}'"
  register: pod_status
  until: pod_status.stdout == "Running"
  delegate_to: "{{ groups.deploy[0] }}"
  retries: 15
  delay: 8

