# etcd 集群间通信的IP和端口, 根据etcd组成员自动生成
TMP_NODES: "{% for h in groups['etcd'] %}{{ hostvars[h]['inventory_hostname'] }}=https://{{ hostvars[h]['inventory_hostname'] }}:2380,{% endfor %}"
ETCD_NODES: "{{ TMP_NODES.rstrip(',') }}"
