## ---------docker daemon配置部分-----------
- name: 准备docker相关目录
  file: name={{ item }} state=directory
  with_items:
  - '{{ DOCKER_DIR }}'

- name: 下载 docker 二进制文件
  copy: src={{ BASE_DOCKER_DIR }}/{{ item }} dest={{ BIN_DIR }}/{{ item }} mode=0755
  with_items:
  - containerd
  - containerd-shim
  - ctr
  - docker
  - dockerd
  - docker-init
  - docker-proxy
  - runc
  tags: upgrade_docker, download_docker

- name: docker命令自动补全
  copy: src=docker.sh dest=/etc/profile.d/docker.sh mode=0644

- name: docker国内镜像加速
  template: src=daemon.json.j2 dest={{ DOCKER_DIR }}/daemon.json

- name: flush-iptables
  shell: "iptables -F && iptables -X \
        && iptables -F -t nat && iptables -X -t nat \
        && iptables -F -t raw && iptables -X -t raw \
        && iptables -F -t mangle && iptables -X -t mangle"

- name: 创建docker的systemd unit文件
  template: src=docker.service.j2 dest={{ SYSTEMD_DIR }}/docker.service
  tags: upgrade_docker, download_docker

- name: 开机启用docker 服务
  shell: systemctl enable docker
  ignore_errors: true

- name: 开启docker 服务
  shell: systemctl daemon-reload && systemctl restart docker
  tags: upgrade_docker

